---
version: "3.9"
services:
  # linux gcc debug build
  raylib-examples-gcc-debug-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: linux-build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
  # linux gcc release build
  raylib-examples-gcc-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: linux-build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
  # windows (mingw) release build
  raylib-examples-mingw-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: windows-build
    environment:
      TARGET: all
      BUILD_TYPE: Release
  # web release build
  raylib-examples-web-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-build
    environment:
      TARGET: all
      BUILD_TYPE: Release
  # rpi (Desktop) release build
  raylib-examples-rpi4-desktop-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: rpi4-desktop-build
    environment:
      TARGET: all
      BUILD_TYPE: Release
  # rpi4 release build
  raylib-examples-rpi4-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: rpi4-build
    environment:
      TARGET: all
      BUILD_TYPE: Release
  # android release build
  raylib-examples-android-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: android-build
    environment:
      TARGET: all
      BUILD_TYPE: Release