#!/bin/bash

$CMAKE -B build -S . -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
    -DCMAKE_C_FLAGS="-I/opt/vc/include -I${ARCHLINUX_ARM_INCLUDES_DIR} -I${ARCHLINUX_ARM_LOCAL_INCLUDES_DIR}" \
    -DCMAKE_CXX_FLAGS="-I/opt/vc/include -I${ARCHLINUX_ARM_INCLUDES_DIR} -I${ARCHLINUX_ARM_LOCAL_INCLUDES_DIR}" \
    ${RAYLIB_CMAKE_ARGS} ${RAYLIB_ADDITIONAL_CMAKE_ARGS} \
    ${CMAKE_ARGS}

cd build
$MAKE "${TARGET}"