#!/bin/bash

$CMAKE -B build -S . -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
    -DCMAKE_C_FLAGS="-I${NATIVE_APP_GLUE_PATH}" \
    -DCMAKE_CXX_FLAGS="-I${NATIVE_APP_GLUE_PATH}" \
    ${RAYLIB_CMAKE_ARGS} ${RAYLIB_ADDITIONAL_CMAKE_ARGS} \
    ${CMAKE_ARGS}

cd build
$MAKE "${TARGET}"