#!/bin/bash

$CMAKE -B "${RAYLIB_BINARY_DIR}" -S "${RAYLIB_SOURCE_DIR}" -G "${CMAKE_GENERATOR}" -DCMAKE_TOOLCHAIN_FILE="${TOOLCHAIN_FILE}" \
    ${RAYLIB_CMAKE_ARGS} \
    ${RAYLIB_ADDITIONAL_CMAKE_ARGS}

$CMAKE --build ${RAYLIB_BINARY_DIR}