#!/bin/bash

$CMAKE -B "${RAYLIB_BINARY_DIR}" -S "${RAYLIB_SOURCE_DIR}" -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
    -DCMAKE_C_FLAGS="-I${NATIVE_APP_GLUE_PATH}" \
    -DCMAKE_CXX_FLAGS="-I${NATIVE_APP_GLUE_PATH}" \
    ${RAYLIB_CMAKE_ARGS} \
    ${RAYLIB_ADDITIONAL_CMAKE_ARGS} \
    -DBUILD_EXAMPLES=OFF

cd "${RAYLIB_BINARY_DIR}" 
${MAKE} raylib