---
version: "3.9"
services:
  # linux gcc debug build
  example-gcc-debug-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Debug
      CMAKE_GENERATOR: Ninja
    volumes:
      - ./build-linux:/home/project/build
  # linux gcc release build
  example-gcc-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: linux-build
    environment:
      CC: gcc
      CXX: g++
      TARGET: all
      BUILD_TYPE: Release
      CMAKE_GENERATOR: Ninja
    volumes:
      - ./build-linux:/home/project/build
  # windows (mingw) release build
  example-mingw-release-build-raylib:
    build:
      context: .
      dockerfile: Dockerfile
      target: windows-build
    environment:
      TARGET: all
      BUILD_TYPE: Release
    volumes:
      - ./build-mingw:/home/project/build